const course = [
	{
		title: "The Complete JavaScript Course 2020: Build Real Projects!",
		author: "Jonas Schmedtmann",
		rating: 4.6,
		price: 134.99,
		courseImage: "https://i.imgur.com/JXLmAAQ.jpg",
	},
	{
		title: "The Python Mega Course: Build 10 Real World Applications",
		author: "Leanne Graham",
		rating: 5,
		price: 149.99,
		courseImage: "https://i.imgur.com/kNULtoW.jpg",
	},
	{
		title: "Java Programming Masterclass for Software Developers",
		author: "Clementine Bauch",
		rating: 3.5,
		price: 249.99,
		courseImage: "https://i.imgur.com/EhcI9UI.jpg",
	},
	{
		title: "C Programming Masterclass for Software Developers",
		author: "Patricia Lebsack",
		rating: 4,
		price: 199.99,
		courseImage: "https://i.imgur.com/kc8Hwkj.jpg",
	},
	{
		title: "Complete C++ course , Beginner to Advanced",
		author: "Maximilian Schwarzmüller",
		rating: 5,
		price: 399.99,
		courseImage: "https://i.imgur.com/W2rqi4L.jpg",
	},
	{
		title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
		author: "Academind by Maximilian Schwarzmüller, Maximilian Schwarzmüller",
		rating: 5,
		price: 199.99,
		courseImage: "https://i.imgur.com/LGcizyU.jpg",
	},
	{
		title: "Complete PHP course, Beginner to Advanced",
		author: "Stephen Grider",
		rating: 5,
		price: 299.99,
		courseImage: "https://i.imgur.com/w6BSfqb.jpg",
	},
	{
		title: "C# for complete beginner",
		author: "Robert Bunch",
		rating: 5,
		price: 399.99,
		courseImage: "https://i.imgur.com/gDRR9WO.jpg",
	},
	{
		title: "Swift for complete beginner",
		author: "Brad Schiff",
		rating: 5,
		price: 199.99,
		courseImage: "https://i.imgur.com/0nd4eVY.jpg",
	},
	{
		title: "Ruby for web developing",
		author: "Andrew Mead",
		rating: 5,
		price: 99.99,
		courseImage: "https://i.imgur.com/lxhZXIO.jpg",
	},
	{
		title: "Complete Angular course for web developing",
		author: "Colt Steele",
		rating: 2,
		price: 79.99,
		courseImage: "https://i.imgur.com/o0uSehi.jpg",
	},
	{
		title: "Typescript course for advanced javascript developer",
		author: "Development Island (UK)",
		rating: 5,
		price: 69.99,
		courseImage: "https://i.imgur.com/0HOs1Qb.jpg",
	},
	{
		title: "HTML course for complete beginner",
		author: "Andrei Neagoie",
		rating: 4,
		price: 199.99,
		courseImage: "https://i.imgur.com/SlF0dZ7.jpg",
	},
	{
		title: "CSS course for web designer",
		author: "Evan Kimbrell",
		rating: 3,
		price: 79.99,
		courseImage: "https://i.imgur.com/srGsmlD.jpg",
	},
	{
		title: "NodeJS from beginner to advance",
		author: "Clementina DuBuque",
		rating: 5,
		price: 69.99,
		courseImage: "https://i.imgur.com/5AvUdai.jpg",
	},
];

export default course;